language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install -e .[test]
  # - pip install coveralls

# command to run tests
script: 
  - py.test src --cov=src --cov-report term-missing

after_success:
  # - coveralls

notifications:
  email: false